chore: fix success requirement

diff --git a/.github/workflows/ci.yaml b/.github/workflows/ci.yaml
--- a/.github/workflows/ci.yaml
+++ b/.github/workflows/ci.yaml
@@ -77,7 +77,12 @@ jobs:
   success:
     name: Success
     needs: [checks, tests]
+    if: success() || failure()
     runs-on: ubuntu-latest
     steps:
       - name: Success
+        if: success()
         run: echo "Success!"
+      - name: Failure
+        if: failure()
+        run: echo "Failure!"; exit 1
